<?php

namespace Milwad\LaravelCrod\Tests;

class MakeQueryTest extends BaseTest
{
    /**
     * @var string
     */
    private string $command = 'crud:query';

    /**
     * @var string
     */
    private string $model = 'Product';

    /**
     * @var string
     */
    private string $table_name = 'products';

    /**
     * Define environment setup.
     *
     * @param \Illuminate\Foundation\Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
//        $this->artisan('migrate', ['--database' => 'testbench'])->run();
    }

    /**
     * Test when user run 'crud:query' command, add query successfully.
     *
     * @test
     * @return void
     */
    public function when_user_run_crud_query_command_add_query_successfully()
    {
//        $this->artisan('crud:make', ['name' => 'Product']);
//
//        $this->artisan($this->command, [
//            'model' => $this->model,
//            'table_name' => $this->table_name
//        ]);
    }
}